CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS sensus_keluarga (
  id BIGSERIAL PRIMARY KEY,
  nomor_kk VARCHAR(32),
  nama_kepala_keluarga TEXT,
  nama_responden TEXT,
  nama_enumerator_mahasiswa TEXT,
  alamat_lengkap TEXT,
  nomor_hp VARCHAR(32),
  periode_pendataan TEXT,
  titik_koordinat_x DECIMAL(14,8),
  titik_koordinat_y DECIMAL(14,8),
  geom GEOMETRY(Point, 4326) GENERATED ALWAYS AS (
    CASE
      WHEN titik_koordinat_x IS NULL OR titik_koordinat_y IS NULL THEN NULL
      ELSE ST_SetSRID(ST_MakePoint(titik_koordinat_x::double precision, titik_koordinat_y::double precision), 4326)
    END
  ) STORED,
  jumlah_anggota_dalam_keluarga BIGINT,
  jumlah_anggota_yang_benar_benar_tinggal_dirumah_ini BIGINT,
  jumlah_balita_0_5_tahun BIGINT,
  jumlah_anak_anak_6_12_tahun BIGINT,
  jumlah_remaja_produktif_13_59_tahun BIGINT,
  jumlah_lansia_60_tahun_ke_atas BIGINT,
  apakah_ada_anak_yang_putus_sekolah_kalau_ada_berapa_dan_sebutkan_nama_nama_dan_kapan_berhenti_sekolah_nya_sd_smp_sma TEXT,
  tempat_tinggal_yang_ditempati TEXT,
  status_tanah_bangunan_tempat_tinggal_yang_ditempati TEXT,
  apakah_terdapat_retakan_pada_bangunan TEXT,
  apakah_kepemilikan_lahan_tempat_tinggal_memiliki_dokumen_yang_resmi TEXT,
  luas_rumah DECIMAL(14,2),
  luas_sawah DECIMAL(14,2),
  luas_kebun_tanaman_muda DECIMAL(14,2),
  luas_kebun_tanaman_tua DECIMAL(14,2),
  luas_lahan_kosong DECIMAL(14,2),
  intensitas_tanam_padi_dalam_setahun TEXT,
  rata_rata_produksi_panen_padi_pangan_lainnya_per_musim_panen TEXT,
  luas_kolam_ikan DECIMAL(14,2),
  jenis_lantai_tempat_tinggal_terluas TEXT,
  jenis_dinding_sebagian_besar_rumah TEXT,
  kondisi_ventilasi_rumah TEXT,
  jenis_atap TEXT,
  penerangan_rumah TEXT,
  besar_daya_listrik_pln TEXT,
  energi_untuk_memasak TEXT,
  tempat_pembuangan_sampah TEXT,
  fasilitas_mck TEXT,
  apakah_akses_jalan_rumah_pernah_terputus_akibat_bencana TEXT,
  fasilitas_jamban TEXT,
  jenis_kloset TEXT,
  sumber_air_mandi_terbanyak_dari TEXT,
  sumber_air_minum_terbanyak_dari TEXT,
  tempat_pembuangan_air_limbah_septic_tank TEXT,
  kondisi_drainase_disekitar_rumah TEXT,
  rumah_berada_di_bawah_sutet_sutt_suttas TEXT,
  rumah_di_lereng_bukit_gunung TEXT,
  secara_keseluruhan_kondisi_rumah TEXT,
  data_kejadian_bencana TEXT,
  blt_dana_desa TEXT,
  bpjs_kis TEXT,
  program_keluarga_harapan_pkh TEXT,
  bantuan_sosial_tunai TEXT,
  bantuan_rehap_rumah_tidak_layak_huni TEXT,
  bantuan_pendidikan_anak TEXT,
  bantuan_lainnya TEXT,
  berapa_rata_rata_pegeluaran_keluarga_dalam_sebulan_rupiah BIGINT,
  kepemilikin_aset TEXT,
  apakah_memelihara_ternak TEXT,
  jumlah_kepemilikan_bidang_tanah BIGINT,
  jumlah_lembar_pbb BIGINT,
  nomor_nop_pbb VARCHAR(32),
  apakah_mempunyai_umkm TEXT,
  bantuan_umkm TEXT,
  jika_punya_apa_nama_usahanya_dan_dibidang_apa TEXT,
  lokasi_usaha TEXT,
  permasalahan_nomor_induk_berusaha_nib_dan_sertifikat_halal_pada_umkm TEXT,
  perkiraan_pendapatan_bulanan_pelaku_umkm_per_bulan TEXT,
  apakah_lokasi_usahanya_sudah_ada_di_google_maps TEXT,
  apakah_sudah_mengetahui_metode_pembayaran_qris TEXT,
  apakah_ingin_membuat_qris_di_usahanya TEXT,
  kendala_utama_usaha TEXT,
  foto_kk TEXT,
  foto_buku_nikah TEXT,
  rumah_tampak_depan TEXT,
  dalam_rumah_ruang_tamu TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sensus_keluarga_geom_idx ON sensus_keluarga USING GIST (geom);
