-- ==============================================================================
-- SKEMA POSTGRESQL / POSTGIS DATA SENSUS INTISARI (75 PERTANYAAN CORE)
-- All columns VARCHAR(500) / TEXT for flexible survey imports
-- ==============================================================================

DROP TABLE IF EXISTS sensus_keluarga CASCADE;

CREATE TABLE sensus_keluarga (
  id SERIAL PRIMARY KEY,
  nomor_kk VARCHAR(500),
  nama_kepala_keluarga VARCHAR(500),
  nomor_hp VARCHAR(500),
  titik_koordinat_x VARCHAR(500),
  titik_koordinat_y VARCHAR(500),
  tempat_tinggal_yang_ditempati VARCHAR(500),
  status_tanah_bangunan_tempat_tinggal_yang_ditempati VARCHAR(500),
  apakah_kepemilikan_lahan_tempat_tinggal_memiliki_dokumen_yang_resmi TEXT,
  luas_rumah VARCHAR(500),
  jenis_lantai_tempat_tinggal_terluas VARCHAR(500),
  jenis_dinding_sebagian_besar_rumah VARCHAR(500),
  jenis_atap VARCHAR(500),
  penerangan_rumah VARCHAR(500),
  besar_daya_listrik_pln VARCHAR(500),
  energi_untuk_memasak VARCHAR(500),
  tempat_pembuangan_sampah VARCHAR(500),
  fasilitas_mck VARCHAR(500),
  sumber_air_mandi_terbanyak_dari VARCHAR(500),
  fasilitas_jamban VARCHAR(500),
  jenis_kloset VARCHAR(500),
  sumber_air_minum_terbanyak_dari VARCHAR(500),
  tempat_pembuangan_air_limbah_septic_tank VARCHAR(500),
  rumah_berada_di_bawah_sutet_sutt_suttas VARCHAR(500),
  rumah_di_lereng_bukit_gunung VARCHAR(500),
  secara_keseluruhan_kondisi_rumah VARCHAR(500),
  blt_dana_desa VARCHAR(500),
  program_keluarga_harapan_pkh VARCHAR(500),
  bantuan_sosial_tunai VARCHAR(500),
  bantuan_umkm VARCHAR(500),
  bantuan_pendidikan_anak VARCHAR(500),
  bantuan_lainnya VARCHAR(500),
  berapa_rata_rata_pegeluaran_keluarga_dalam_sebulan_rupiah VARCHAR(500),
  kepemilikin_aset VARCHAR(500),
  apakah_memelihara_ternak TEXT,
  jumlah_kepemilikan_bidang_tanah VARCHAR(500),
  jumlah_lembar_pbb VARCHAR(500),
  nomor_nop_pbb VARCHAR(500),
  apakah_mempunyai_umkm TEXT,
  jika_punya_apa_nama_usahanya_dan_dibidang_apa VARCHAR(500),
  lokasi_usaha VARCHAR(500),
  apakah_lokasi_usahanya_sudah_ada_di_google_maps TEXT,
  apakah_sudah_mengetahui_metode_pembayaran_qris TEXT,
  apakah_ingin_membuat_qris_di_usahanya TEXT,
  foto_kk TEXT,
  rumah_tampak_depan TEXT,
  dalam_rumah_ruang_tamu TEXT,
  bantuan_rehap_rumah_tidak_layak_huni VARCHAR(500),
  alamat_lengkap VARCHAR(500),
  apakah_ada_anak_yang_putus_sekolah_kalau_ada_berapa_dan_sebutkan_nama_nama_dan_kapan_berhenti_sekolah_nya_sd_smp_sma TEXT,
  foto_buku_nikah TEXT,
  nama_enumerator_mahasiswa VARCHAR(500),
  periode_pendataan VARCHAR(500),
  nama_responden VARCHAR(500),
  jumlah_anggota_dalam_keluarga VARCHAR(500),
  jumlah_anggota_yang_benar_benar_tinggal_dirumah_ini VARCHAR(500),
  kondisi_drainase_disekitar_rumah VARCHAR(500),
  kendala_utama_usaha VARCHAR(500),
  apakah_terdapat_retakan_pada_bangunan TEXT,
  apakah_akses_jalan_rumah_pernah_terputus_akibat_bencana TEXT,
  jumlah_balita_0_5_tahun VARCHAR(500),
  jumlah_anak_anak_6_12_tahun VARCHAR(500),
  jumlah_remaja_produktif_13_59_tahun VARCHAR(500),
  jumlah_lansia_60_tahun_ke_atas VARCHAR(500),
  bpjs_kis VARCHAR(500),
  luas_sawah VARCHAR(500),
  luas_kebun_tanaman_muda VARCHAR(500),
  luas_kebun_tanaman_tua VARCHAR(500),
  luas_lahan_kosong VARCHAR(500),
  luas_kolam_ikan VARCHAR(500),
  intensitas_tanam_padi_dalam_setahun VARCHAR(500),
  rata_rata_produksi_panen_padi_pangan_lainnya_per_musim_panen VARCHAR(500),
  permasalahan_nomor_induk_berusaha_nib_dan_sertifikat_halal_pada_umkm TEXT,
  perkiraan_pendapatan_bulanan_pelaku_umkm_per_bulan VARCHAR(500),
  kondisi_ventilasi_rumah VARCHAR(500),
  data_kejadian_bencana VARCHAR(500),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexing untuk Kecepatan Query & Filter
CREATE INDEX IF NOT EXISTS idx_sensus_nomor_kk ON sensus_keluarga(nomor_kk);
CREATE INDEX IF NOT EXISTS idx_sensus_nama_kk ON sensus_keluarga(nama_kepala_keluarga);
CREATE INDEX IF NOT EXISTS idx_sensus_periode ON sensus_keluarga(periode_pendataan);
